name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: change chromedriver perms
      run: chmod 777 /home/runner/work/DevOpsWebscraper/DevOpsWebscraper/Drivers/chromedriver
    - name: Test
      run: dotnet test --no-build --verbosity normal
